name: Pumplog
options:
  bundleIdPrefix: com.shimondeitel.pumplog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Pumplog:
    type: application
    platform: iOS
    sources:
      - path: Pumplog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.pumplog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Pumplog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  PumplogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PumplogTests
      - path: Pumplog.storekit
    dependencies:
      - target: Pumplog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.pumplog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  PumplogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: PumplogUITests
    dependencies:
      - target: Pumplog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.pumplog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Pumplog:
    build:
      targets:
        Pumplog: all
        PumplogTests: [test]
        PumplogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Pumplog.storekit
    test:
      config: Debug
      storeKitConfiguration: Pumplog.storekit
      targets:
        - PumplogTests
        - PumplogUITests
    archive:
      config: Release
